### Test
This is a test

$y=24$

Thank you for your attention

In [66]:
import time
import numpy as np
import pandas as pd
from numpy import linalg as LA

calculate eigenvalues and eigenvectors for diagonal

In [20]:
w, v = LA.eig(np.diag((1, 2, 3, 4, 5)))
print(w)
print(v)

[1. 2. 3. 4. 5.]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


calculate eigenvalues and eigenvectors for given

In [21]:
A = np.matrix([[1, 0], [0, 1]])

w, v = LA.eig(A)
print(w)
print(v)

[1. 1.]
[[1. 0.]
 [0. 1.]]


verify eigenvalues and eigenvectors

$Av=\lambda v$

In [22]:
A = np.matrix([[1, 0], [0, 1]])
w = 1
v = np.matrix([[1], [1]])

#matrix multiplication
print(A*v)
print(w*v)

[[1]
 [1]]
[[1]
 [1]]


Calculate norms

In [26]:
A = np.matrix([
    [-4, 0, 0, 0, 0, 0],
    [0, 3, 0, 0, 0, 0],
    [0, 0, 5, 0, 0, 0],
    [0, 0, 0, 2, 0, 0],
    [0, 0, 0, 0, -1, 0],
    [0, 0, 0, 0, 0, 3]
])

print(LA.norm(A))
print(LA.norm(A, ord=1))
print(LA.norm(A, 'nuc'))

8.0
5.0
18.0


read csv with col index and encoding

In [ ]:
df = pd.read_csv("data.csv", index_col = 0, encoding = "latin-1")

profiling timer

In [ ]:
start = time.perf_counter()
np.nansum(df)
print(time.perf_counter() - start)